### ISSUE TITLE
fuller screen request

### ISSUE THREAD

**Issue by dima-stefantsov** [DonkeyPacific/obsidian-full-screen-cross-platform-plugin#10]
Hello. Your plugin works great, thanks, but could I please request improvements?
windows10, obsidian1.5.8

1. It does not enable the default F11 fullscreen, that hides the windows taskbar. I've achieved it with autohotkey snippet
```
#IfWinActive, ahk_exe Obsidian.exe
    $F11::SendInput {F13}{F11}
#IfWinActive
```
, but it would be nicer to have it built-in. Maybe as an additional toggle option in Settings.

2. right now when enabling fullscreen, I can still see:

top-left
![image](https://github.com/user-attachments/assets/9e435b35-44bf-45a2-927c-ed12dcc77e6a)

top-middle
![image](https://github.com/user-attachments/assets/78cce19f-b596-4a5e-b6da-f2c37254c32a)

top-right
![image](https://github.com/user-attachments/assets/b07ba26b-9665-48dd-9caf-43165506250d)

bottom-right
![image](https://github.com/user-attachments/assets/47dc14e5-2d2b-43db-90a5-231ac5259a96)

top-right in graph view
![image](https://github.com/user-attachments/assets/84c83334-8ecc-455e-919c-6500b34a9610)

I'd obviously like to not have it displayed!
If needed, again, it could be a toggle in Settings, for those who'd want it remaining.

3. when (2) is done, now the only interface element that would taint the view would be a scroll bar. I'm not sure if I want it or not, but a toggle Setting to hide it while in fullscreen mode would also be nice.

I think the Hider obsidian plugin can do all of that, but it does not have a hotkey to apply it, can just toggle it in Settings permanently, which is obviously not what I want.

4. I see you add `fullscreen-cross-platform-hidden` class to elements you are hiding. Could you also add a custom class to the `<body>`? I may want my custom selectors to for example hide items requested in (2) and (3) manually.
Actually, obsidian adds `is-fullscreen` upon the native F11 fullscreen, I didn't want to write each selector `display:none!important;` manually, and then supporting it through obsidian updates, thought someone has probably already solved that with a plugin :)

**Comment by dima-stefantsov** [comment]
native css to achieve it all upon pressing F11
```css
/* fullscreen clear */
.is-fullscreen .mod-sidedock,
.is-fullscreen .workspace-tab-header-container,
.is-fullscreen .view-header,
.is-fullscreen .workspace-ribbon,
.is-fullscreen .status-bar,
.is-fullscreen .graph-controls,
.is-fullscreen .cm-scroller::-webkit-scrollbar,
.is-fullscreen .markdown-rendered::-webkit-scrollbar {
    display: none !important;
}
```
